-- Complete Schema for ActaNex V3
CREATE TABLE IF NOT EXISTS app_settings (
    id TEXT PRIMARY KEY,
    mileage_rate_business REAL NOT NULL DEFAULT 0.30,
    commute_rate_tier1 REAL NOT NULL DEFAULT 0.30,
    commute_rate_tier2 REAL NOT NULL DEFAULT 0.38,
    vma_rate_8h REAL NOT NULL DEFAULT 14.00,
    vma_rate_24h REAL NOT NULL DEFAULT 28.00,
    pdf_storage_mode TEXT NOT NULL DEFAULT 'R2',
    updated_at_utc TEXT NOT NULL,
    email_sender_name TEXT,
    email_sender_email TEXT,
    email_service TEXT,
    email_api_key TEXT,
    email_subject_template TEXT,
    email_body_template TEXT,
    email_reminder1_subject TEXT,
    email_reminder1_body TEXT,
    email_reminder2_subject TEXT,
    email_reminder2_body TEXT,
    email_admin_notify_rejection INTEGER DEFAULT 1,
    email_admin_notify_reminder INTEGER DEFAULT 1,
    contractor_signature_data_url TEXT,
    contractor_title TEXT,
    billing_provider TEXT DEFAULT 'none',
    chart_of_accounts TEXT DEFAULT 'SKR04',
    tax_mode TEXT DEFAULT 'standard',
    datev_consultant_number TEXT DEFAULT '1001',
    datev_client_number TEXT DEFAULT '10001'
);

CREATE TABLE IF NOT EXISTS customers (
    id TEXT PRIMARY KEY,
    lexware_contact_id TEXT NOT NULL UNIQUE,
    customer_number TEXT,
    name TEXT NOT NULL,
    contact_person TEXT,
    email TEXT,
    street TEXT,
    zip_code TEXT,
    city TEXT,
    country_code TEXT DEFAULT 'DE',
    vat_id TEXT,
    is_active INTEGER NOT NULL DEFAULT 1,
    is_archived INTEGER NOT NULL DEFAULT 0,
    created_at_utc TEXT NOT NULL,
    updated_at_utc TEXT
);

CREATE TABLE IF NOT EXISTS projects (
    id TEXT PRIMARY KEY,
    customer_id TEXT NOT NULL,
    project_number TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    purchase_order_number TEXT,
    contract_number TEXT,
    default_hourly_rate REAL NOT NULL DEFAULT 120.00,
    planned_hours REAL DEFAULT 0.0,
    total_budget_net REAL DEFAULT 0.0,
    lexware_service_article_id TEXT NOT NULL,
    billing_interval_minutes INTEGER NOT NULL DEFAULT 15,
    billing_rounding_rule TEXT DEFAULT 'exact',
    approver_email TEXT NOT NULL,
    approver_name TEXT,
    travel_time_billable INTEGER NOT NULL DEFAULT 0,
    travel_time_rate_multiplier REAL NOT NULL DEFAULT 1.0,
    public_transit_reimbursable INTEGER NOT NULL DEFAULT 1,
    start_date TEXT,
    end_date TEXT,
    lexware_quotation_number TEXT,
    lexware_order_confirmation_id TEXT,
    is_active INTEGER NOT NULL DEFAULT 1,
    is_archived INTEGER NOT NULL DEFAULT 0,
    created_at_utc TEXT NOT NULL,
    FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS time_entries (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    timesheet_version_id TEXT,
    entry_date TEXT NOT NULL,
    start_time TEXT,
    end_time TEXT,
    duration_hours REAL NOT NULL,
    activity_description TEXT NOT NULL,
    is_billable INTEGER NOT NULL DEFAULT 1,
    created_at_utc TEXT NOT NULL,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS timesheet_versions (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    version_number INTEGER NOT NULL DEFAULT 1,
    period TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'Draft',
    total_actual_hours REAL NOT NULL DEFAULT 0.0,
    total_billable_hours REAL NOT NULL DEFAULT 0.0,
    total_billable_travel_hours REAL NOT NULL DEFAULT 0.0,
    total_reimbursable_expenses REAL NOT NULL DEFAULT 0.0,
    total_amount_net REAL NOT NULL DEFAULT 0.0,
    data_hash_sha256 TEXT NOT NULL,
    pdf_r2_storage_key TEXT,
    pdf_generated_at_utc TEXT,
    signed_document_r2_key TEXT,
    signed_document_filename TEXT,
    signed_document_uploaded_at_utc TEXT,
    signed_document_sha256 TEXT,
    created_at_utc TEXT NOT NULL,
    submitted_at_utc TEXT,
    approved_at_utc TEXT,
    approved_by TEXT,
    approval_method TEXT,
    lexware_invoice_id TEXT,
    lexware_invoice_number TEXT,
    is_invoice_canceled INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS operational_vouchers (
    id TEXT PRIMARY KEY,
    voucher_number TEXT NOT NULL UNIQUE,
    voucher_type TEXT NOT NULL,
    voucher_date TEXT NOT NULL,
    supplier_name TEXT NOT NULL,
    description TEXT NOT NULL,
    business_purpose TEXT NOT NULL,
    project_id TEXT,
    customer_id TEXT,
    is_billable_to_client INTEGER NOT NULL DEFAULT 0,
    amount_gross REAL NOT NULL DEFAULT 0.0,
    amount_net REAL NOT NULL DEFAULT 0.0,
    tax_rate REAL NOT NULL DEFAULT 19.0,
    tax_amount REAL NOT NULL DEFAULT 0.0,
    tax19_gross REAL DEFAULT 0.0,
    tax7_gross REAL DEFAULT 0.0,
    tax19_amount REAL DEFAULT 0.0,
    tax7_amount REAL DEFAULT 0.0,
    tip_amount REAL NOT NULL DEFAULT 0.0,
    total_attendees_count INTEGER DEFAULT 1,
    business_attendees_count INTEGER DEFAULT 1,
    business_share_percent REAL DEFAULT 100.0,
    tax_deductible_net REAL DEFAULT 0.0,
    tax_non_deductible_net REAL DEFAULT 0.0,
    private_share_gross REAL DEFAULT 0.0,
    attendees_json TEXT,
    location_address TEXT,
    is_own_receipt INTEGER NOT NULL DEFAULT 0,
    own_receipt_reason TEXT,
    transport_type TEXT,
    distance_km REAL DEFAULT 0.0,
    origin_address TEXT,
    destination_address TEXT,
    trip_id TEXT,
    parent_hospitality_voucher_id TEXT,
    skr04_account TEXT NOT NULL DEFAULT '4650',
    skr03_account TEXT NOT NULL DEFAULT '4650',
    receipt_r2_key TEXT,
    receipt_filename TEXT,
    receipt_mime_type TEXT,
    payment_slip_r2_key TEXT,
    payment_slip_filename TEXT,
    payment_slip_total_gross REAL DEFAULT 0.0,
    payment_method TEXT DEFAULT 'Card_NFC',
    secondary_attachment_r2_key TEXT,
    secondary_attachment_filename TEXT,
    voucher_pdf_r2_key TEXT,
    voucher_pdf_hash_sha256 TEXT,
    is_synced_to_lexware INTEGER NOT NULL DEFAULT 0,
    lexware_voucher_id TEXT,
    lexware_voucher_number TEXT,
    lexware_status TEXT DEFAULT 'open',
    status TEXT DEFAULT 'Verified',
    created_at_utc TEXT NOT NULL,
    updated_at_utc TEXT
);

CREATE TABLE IF NOT EXISTS merchant_rules (
    id TEXT PRIMARY KEY,
    pattern TEXT NOT NULL UNIQUE,
    merchant_name TEXT NOT NULL,
    category TEXT NOT NULL,
    skr04_account TEXT NOT NULL,
    default_tax_rate REAL NOT NULL DEFAULT 19.0,
    auto_apply INTEGER NOT NULL DEFAULT 1,
    confidence_boost REAL NOT NULL DEFAULT 0.95,
    learned_from_voucher_id TEXT,
    created_at_utc TEXT NOT NULL,
    updated_at_utc TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS trips (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    trip_date TEXT NOT NULL,
    purpose TEXT NOT NULL,
    start_time TEXT,
    end_time TEXT,
    departure_location TEXT NOT NULL,
    destination_location TEXT NOT NULL,
    distance_km REAL NOT NULL DEFAULT 0.0,
    transport_mode TEXT NOT NULL DEFAULT 'Car',
    travel_time_hours REAL NOT NULL DEFAULT 0.0,
    travel_expense_type TEXT NOT NULL DEFAULT 'FlatRate',
    is_customer_billable INTEGER NOT NULL DEFAULT 0,
    is_commute INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'Planned',
    created_at_utc TEXT NOT NULL,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS audit_events (
    id TEXT PRIMARY KEY,
    event_type TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    actor TEXT NOT NULL,
    description TEXT NOT NULL,
    data_payload_json TEXT,
    timestamp_utc TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS admin_users (
    id TEXT PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    salt_hex TEXT NOT NULL,
    display_name TEXT,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at_utc TEXT NOT NULL,
    last_login_at_utc TEXT
);
