const fs = require('node:fs');
const {execFileSync} = require('node:child_process');
for (const file of ['worker.bundle.js','update-release.json']) {
  const name = `src/Worker/bundle/${file}`;
  const expected = execFileSync('git',['show',`HEAD:${name}`],{maxBuffer:10*1024*1024});
  const actual = fs.readFileSync(name);
  if (expected.equals(actual)) {
    console.log(`${file}: reproducible`);
  } else {
    process.exitCode = 1;
    console.error(`${file}: generated artifact differs (${expected.length} committed, ${actual.length} generated bytes)`);
    if (file.endsWith('.json')) {
      const a=JSON.parse(expected),b=JSON.parse(actual);
      for(const key of Object.keys(a)) if(JSON.stringify(a[key])!==JSON.stringify(b[key])) console.error(`Changed release field: ${key}`);
    } else {
      let i=0;while(i<Math.min(expected.length,actual.length)&&expected[i]===actual[i])i++;
      console.error(`First difference at byte ${i}: ${JSON.stringify(expected.subarray(i,i+100).toString())} -> ${JSON.stringify(actual.subarray(i,i+100).toString())}`);
    }
  }
}
